In [1]:
from nba_api.stats.endpoints import LeagueDashTeamStats
from nba_api.stats.endpoints import LeagueGameLog
import pandas as pd

In [2]:
df_team = (
    LeagueDashTeamStats (
        season= '2023-24',
        season_type_all_star='Regular Season'
    )
    .get_data_frames()[0]
)

In [3]:
df_games_1 = (
    LeagueGameLog(
        season = '2024-25',
        season_type_all_star='Regular Season'
    ).get_data_frames()[0]
)

df_games_2 = (
    LeagueGameLog(
        season = '2024-25',
        season_type_all_star='Playoffs'
    ).get_data_frames()[0]
)

df_games = pd.concat([df_games_1, df_games_2], ignore_index=True)

df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,35,47,17,4,1,16,22,103,-7,1
1,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,29,34,20,2,3,12,12,109,-23,1
2,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,29,40,33,6,3,4,15,132,23,1
3,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,31,46,22,7,8,7,22,110,7,1
4,22024,1610612741,CHI,Chicago Bulls,0022400069,2024-10-23,CHI @ NOP,L,240,42,...,38,47,26,4,2,21,16,111,-12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2555,42024,1610612744,GSW,Golden State Warriors,0042400231,2025-05-06,GSW @ MIN,W,240,34,...,33,51,26,10,2,18,18,99,11,1
2556,42024,1610612743,DEN,Denver Nuggets,0042400222,2025-05-07,DEN @ OKC,L,240,33,...,25,38,18,4,6,21,29,106,-43,1
2557,42024,1610612760,OKC,Oklahoma City Thunder,0042400222,2025-05-07,OKC vs. DEN,W,240,50,...,36,44,31,12,8,9,24,149,43,1
2558,42024,1610612752,NYK,New York Knicks,0042400212,2025-05-07,NYK @ BOS,W,240,37,...,36,46,19,11,5,16,16,91,1,1
2559,42024,1610612738,BOS,Boston Celtics,0042400212,2025-05-07,BOS vs. NYK,L,240,34,...,35,51,17,9,5,17,17,90,-1,1

In [4]:
df_games['WIN'] = (df_games['WL'] == 'W').astype(int)
print(df_games)

     SEASON_ID     TEAM_ID TEAM_ABBREVIATION               TEAM_NAME  \
0        22024  1610612750               MIN  Minnesota Timberwolves
1        22024  1610612752               NYK         New York Knicks
2        22024  1610612738               BOS          Boston Celtics
3        22024  1610612747               LAL      Los Angeles Lakers
4        22024  1610612741               CHI           Chicago Bulls
...        ...         ...               ...                     ...
2555     42024  1610612744               GSW   Golden State Warriors
2556     42024  1610612743               DEN          Denver Nuggets
2557     42024  1610612760               OKC   Oklahoma City Thunder
2558     42024  1610612752               NYK         New York Knicks
2559     42024  1610612738               BOS          Boston Celtics

         GAME_ID   GAME_DATE      MATCHUP WL  MIN  FGM  ...  REB  AST  STL  \
0     0022400062  2024-10-22    MIN @ LAL  L  240   35  ...   47   17    4
1     0022400061  2024-10-22    NYK @ BOS  L  240   43  ...   34   20    2
2     0022400061  2024-10-22  BOS vs. NYK  W  240   48  ...   40   33    6
3     0022400062  2024-10-22  LAL vs. MIN  W  240   42  ...   46   22    7
4     0022400069  2024-10-23    CHI @ NOP  L  240   42  ...   47   26    4
...          ...         ...          ... ..  ...  ...  ...  ...  ...  ...
2555  0042400231  2025-05-06    GSW @ MIN  W  240   34  ...   51   26   10
2556  0042400222  2025-05-07    DEN @ OKC  L  240   33  ...   38   18    4
2557  0042400222  2025-05-07  OKC vs. DEN  W  240   50  ...   44   31   12
2558  0042400212  2025-05-07    NYK @ BOS  W  240   37  ...   46   19   11
2559  0042400212  2025-05-07  BOS vs. NYK  L  240   34  ...   51   17    9

      BLK  TOV  PF  PTS  PLUS_MINUS  VIDEO_AVAILABLE  WIN
0       1   16  22  103          -7                1    0
1       3   12  12  109         -23                1    0
2       3    4  15  132          23                1    1
3       8    7  22  110           7                1    1
4       2   21  16  111         -12                1    0
...   ...  ...  ..  ...         ...              ...  ...
2555    2   18  18   99          11                1    1
2556    6   21  29  106         -43                1    0
2557    8    9  24  149          43                1    1
2558    5   16  16   91           1                1    1
2559    5   17  17   90          -1                1    0

[2560 rows x 30 columns]

In [5]:
features = ['TEAM_ID', 'W_PCT', 'PTS_RANK', 'AST_RANK', 'REB_RANK']
season_team_features = df_team[features]
print(season_team_features)

       TEAM_ID  W_PCT  PTS_RANK  AST_RANK  REB_RANK
0   1610612737  0.439         5        16         6
1   1610612738  0.780         2        14         2
2   1610612751  0.390        25        20        11
3   1610612766  0.256        28        26        30
4   1610612741  0.476        22        23        14
5   1610612739  0.585        20         8        17
6   1610612742  0.610         7        19        21
7   1610612743  0.695        14         3         7
8   1610612765  0.171        27        22        16
9   1610612744  0.561         8         4         1
10  1610612745  0.500        16        25         3
11  1610612754  0.573         1         1        28
12  1610612746  0.622        12        21        19
13  1610612747  0.573         6         5        18
14  1610612763  0.329        30        27        24
15  1610612748  0.561        26        18        26
16  1610612749  0.598         4        17         9
17  1610612750  0.683        18        15        15
18  1610612740  0.598        13        13        13
19  1610612752  0.610        19        29         5
20  1610612760  0.695         3        11        27
21  1610612753  0.573        24        28        25
22  1610612755  0.573        15        24        20
23  1610612756  0.598        10        12        10
24  1610612757  0.256        29        30        22
25  1610612758  0.561         9         7        12
26  1610612759  0.268        23         2         8
27  1610612761  0.305        21         6        23
28  1610612762  0.378        11        10         3
29  1610612764  0.183        17         9        29

In [6]:
df_games_with_season_stats = df_games.merge (
    season_team_features,
    on = 'TEAM_ID',
    how = 'left'
)

In [7]:
df_games_with_season_stats

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,WIN,W_PCT,PTS_RANK,AST_RANK,REB_RANK
0,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,16,22,103,-7,1,0,0.683,18,15,15
1,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,12,12,109,-23,1,0,0.610,19,29,5
2,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,4,15,132,23,1,1,0.780,2,14,2
3,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,7,22,110,7,1,1,0.573,6,5,18
4,22024,1610612741,CHI,Chicago Bulls,0022400069,2024-10-23,CHI @ NOP,L,240,42,...,21,16,111,-12,1,0,0.476,22,23,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2555,42024,1610612744,GSW,Golden State Warriors,0042400231,2025-05-06,GSW @ MIN,W,240,34,...,18,18,99,11,1,1,0.561,8,4,1
2556,42024,1610612743,DEN,Denver Nuggets,0042400222,2025-05-07,DEN @ OKC,L,240,33,...,21,29,106,-43,1,0,0.695,14,3,7
2557,42024,1610612760,OKC,Oklahoma City Thunder,0042400222,2025-05-07,OKC vs. DEN,W,240,50,...,9,24,149,43,1,1,0.695,3,11,27
2558,42024,1610612752,NYK,New York Knicks,0042400212,2025-05-07,NYK @ BOS,W,240,37,...,16,16,91,1,1,1,0.610,19,29,5
2559,42024,1610612738,BOS,Boston Celtics,0042400212,2025-05-07,BOS vs. NYK,L,240,34,...,17,17,90,-1,1,0,0.780,2,14,2

In [8]:
from nba_api.stats.static import teams
team_name_to_id = {}
for t in teams.get_teams():
    team_name_to_id[t['abbreviation']] = t['id']

In [9]:
# team, vs, opp = df_games_with_season_stats['MATCHUP'][0].split()

# opponent ID and home advantage

new_col = []
home_col = []
for line in df_games_with_season_stats['MATCHUP']:
    team, vs, opp = line.split()
    if vs != '@':
        home_col.append(1)
    else:
        home_col.append(0)
    new_col.append(team_name_to_id[opp])

df_games_with_season_stats['OPP_ID'] = new_col
df_games_with_season_stats['is_home'] = home_col

In [10]:
def elo_win_prob(elo_a, elo_b):
    pt1 = 1 + pow(10, (elo_b - elo_a)/400)
    return 1 / pt1

In [11]:
# elo rankings for the teams as the season goes on

team_elos = {}
for id in df_games_with_season_stats['TEAM_ID'].unique():
    team_elos[id] = 1500


K = 20 # learning rate, essentially how dramatically the ranking moves game by game
# whether the team loses or wins

pre_elo = []
pre_opp_elo = []
df_games_with_season_stats = df_games_with_season_stats.sort_values(['GAME_DATE','TEAM_ID']).reset_index(drop=True)

for _, r in df_games_with_season_stats.iterrows():
    team_id = r['TEAM_ID']
    opp_id = r['OPP_ID']

   
    e_t = team_elos[team_id]
    e_o = team_elos[opp_id]
    
    pre_elo.append(e_t)
    pre_opp_elo.append(e_o)

    expected_prob = elo_win_prob(e_t, e_o)
    s_a = r['WIN']


    team_elos[team_id] = e_t + K * (s_a - expected_prob)
    team_elos[opp_id] = e_o + K * ((1 - s_a) - (1 - expected_prob))

    # s_a is the actual value (whether the team won or lost)
    # expected_prob is the expected score from the formula based on the teams ELOS
    # a team will outperform its expectation if s_a - expected_prob is greater than 0
    #     as a result the team's ELO would go up, otherwise it will go down
    
df_games_with_season_stats['elo'] = pre_elo
df_games_with_season_stats['elo_opp'] = pre_opp_elo
df_games_with_season_stats['elo_diff'] = df_games_with_season_stats['elo'] - df_games_with_season_stats['elo_opp']

In [12]:
# momentum
df_games_with_season_stats['momentum_5'] = (
    df_games_with_season_stats.groupby('TEAM_ID')['WIN']
        .rolling(window = 5, min_periods=1)
        .mean()
        .shift(1) # prevent leakage of knowing the Game N's result
        .reset_index(level=0, drop=True)
)

df_games_with_season_stats['momentum_5'] = df_games_with_season_stats['momentum_5'].fillna(0)

In [13]:
# win streak
win_streak = []
map_to_streak = {}
keys = []
for _, r in df_games_with_season_stats.iterrows():
    keys.append(r['TEAM_ID'])

map_to_streak = dict.fromkeys(keys, 0)
print(map_to_streak)

for _, r in df_games_with_season_stats.iterrows():
    team_id = r['TEAM_ID']
    result = r['WIN']
    
    if result == 1:
        new_val = map_to_streak[team_id] + 1
        win_streak.append(new_val)
        map_to_streak[team_id] = new_val
    else:
        win_streak.append(0)
        map_to_streak[team_id] = 0

df_games_with_season_stats['win_streak'] = win_streak

{1610612738: 0, 1610612747: 0, 1610612750: 0, 1610612752: 0, 1610612737: 0, 1610612739: 0, 1610612740: 0, 1610612741: 0, 1610612744: 0, 1610612745: 0, 1610612746: 0, 1610612748: 0, 1610612749: 0, 1610612751: 0, 1610612753: 0, 1610612754: 0, 1610612755: 0, 1610612756: 0, 1610612757: 0, 1610612761: 0, 1610612762: 0, 1610612763: 0, 1610612765: 0, 1610612766: 0, 1610612742: 0, 1610612743: 0, 1610612758: 0, 1610612759: 0, 1610612760: 0, 1610612764: 0}

In [14]:
df_games_with_season_stats

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,PTS_RANK,AST_RANK,REB_RANK,OPP_ID,is_home,elo,elo_opp,elo_diff,momentum_5,win_streak
0,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,2,14,2,1610612752,1,1500.000000,1500.000000,0.000000,0.8,1
1,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,6,5,18,1610612750,1,1500.000000,1500.000000,0.000000,0.4,1
2,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,18,15,15,1610612747,0,1490.000000,1510.000000,-20.000000,0.2,0
3,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,19,29,5,1610612738,0,1490.000000,1510.000000,-20.000000,0.2,0
4,22024,1610612737,ATL,Atlanta Hawks,0022400064,2024-10-23,ATL vs. BKN,W,240,39,...,5,16,6,1610612751,1,1500.000000,1500.000000,0.000000,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2555,42024,1610612754,IND,Indiana Pacers,0042400202,2025-05-06,IND @ CLE,W,240,44,...,1,1,28,1610612739,0,1719.072203,1658.601194,60.471009,0.8,4
2556,42024,1610612738,BOS,Boston Celtics,0042400212,2025-05-07,BOS vs. NYK,L,240,34,...,2,14,2,1610612752,1,1694.727655,1605.408502,89.319153,0.6,0
2557,42024,1610612743,DEN,Denver Nuggets,0042400222,2025-05-07,DEN @ OKC,L,240,33,...,14,3,7,1610612760,0,1664.478979,1785.895797,-121.416817,0.8,0
2558,42024,1610612752,NYK,New York Knicks,0042400212,2025-05-07,NYK @ BOS,W,240,37,...,19,29,5,1610612738,0,1617.924136,1682.212020,-64.287884,0.8,3
2559,42024,1610612760,OKC,Oklahoma City Thunder,0042400222,2025-05-07,OKC vs. DEN,W,240,50,...,3,11,27,1610612743,1,1792.536780,1657.837996,134.698785,0.8,1

In [15]:
df_games_with_season_stats = df_games_with_season_stats.merge(
    season_team_features,
    left_on='OPP_ID',
    right_on='TEAM_ID',
    suffixes=('','_opp')
)

In [16]:
df_games_with_season_stats

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,elo,elo_opp,elo_diff,momentum_5,win_streak,TEAM_ID_opp,W_PCT_opp,PTS_RANK_opp,AST_RANK_opp,REB_RANK_opp
0,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,1500.000000,1500.000000,0.000000,0.8,1,1610612752,0.610,19,29,5
1,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,1500.000000,1500.000000,0.000000,0.4,1,1610612750,0.683,18,15,15
2,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,1490.000000,1510.000000,-20.000000,0.2,0,1610612747,0.573,6,5,18
3,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,1490.000000,1510.000000,-20.000000,0.2,0,1610612738,0.780,2,14,2
4,22024,1610612737,ATL,Atlanta Hawks,0022400064,2024-10-23,ATL vs. BKN,W,240,39,...,1500.000000,1500.000000,0.000000,0.0,1,1610612751,0.390,25,20,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2555,42024,1610612754,IND,Indiana Pacers,0042400202,2025-05-06,IND @ CLE,W,240,44,...,1719.072203,1658.601194,60.471009,0.8,4,1610612739,0.585,20,8,17
2556,42024,1610612738,BOS,Boston Celtics,0042400212,2025-05-07,BOS vs. NYK,L,240,34,...,1694.727655,1605.408502,89.319153,0.6,0,1610612752,0.610,19,29,5
2557,42024,1610612743,DEN,Denver Nuggets,0042400222,2025-05-07,DEN @ OKC,L,240,33,...,1664.478979,1785.895797,-121.416817,0.8,0,1610612760,0.695,3,11,27
2558,42024,1610612752,NYK,New York Knicks,0042400212,2025-05-07,NYK @ BOS,W,240,37,...,1617.924136,1682.212020,-64.287884,0.8,3,1610612738,0.780,2,14,2
2559,42024,1610612760,OKC,Oklahoma City Thunder,0042400222,2025-05-07,OKC vs. DEN,W,240,50,...,1792.536780,1657.837996,134.698785,0.8,1,1610612743,0.695,14,3,7

In [17]:
for stat in ['W_PCT', 'PTS_RANK', 'AST_RANK', 'REB_RANK']:
    df_games_with_season_stats[f'{stat}_diff'] = df_games_with_season_stats[stat] - df_games_with_season_stats[f'{stat}_opp']
df_games_with_season_stats

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,win_streak,TEAM_ID_opp,W_PCT_opp,PTS_RANK_opp,AST_RANK_opp,REB_RANK_opp,W_PCT_diff,PTS_RANK_diff,AST_RANK_diff,REB_RANK_diff
0,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,1,1610612752,0.610,19,29,5,0.170,-17,-15,-3
1,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,1,1610612750,0.683,18,15,15,-0.110,-12,-10,3
2,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,0,1610612747,0.573,6,5,18,0.110,12,10,-3
3,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,0,1610612738,0.780,2,14,2,-0.170,17,15,3
4,22024,1610612737,ATL,Atlanta Hawks,0022400064,2024-10-23,ATL vs. BKN,W,240,39,...,1,1610612751,0.390,25,20,11,0.049,-20,-4,-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2555,42024,1610612754,IND,Indiana Pacers,0042400202,2025-05-06,IND @ CLE,W,240,44,...,4,1610612739,0.585,20,8,17,-0.012,-19,-7,11
2556,42024,1610612738,BOS,Boston Celtics,0042400212,2025-05-07,BOS vs. NYK,L,240,34,...,0,1610612752,0.610,19,29,5,0.170,-17,-15,-3
2557,42024,1610612743,DEN,Denver Nuggets,0042400222,2025-05-07,DEN @ OKC,L,240,33,...,0,1610612760,0.695,3,11,27,0.000,11,-8,-20
2558,42024,1610612752,NYK,New York Knicks,0042400212,2025-05-07,NYK @ BOS,W,240,37,...,3,1610612738,0.780,2,14,2,-0.170,17,15,3
2559,42024,1610612760,OKC,Oklahoma City Thunder,0042400222,2025-05-07,OKC vs. DEN,W,240,50,...,1,1610612743,0.695,14,3,7,0.000,-11,8,20

In [55]:
def get_opponent_score(matchup, game_date, df):
    """
    Retrieves the opponent's score from the DataFrame.

    Args:
        matchup (str): The matchup string (e.g., 'TeamA vs TeamB').
        game_date (str): The game date.
        df (pd.DataFrame): The DataFrame containing game data.

    Returns:
        int: The opponent's score, or None if not found.
    """
    team_1, _, team_2 = matchup.split()
    rows_with_value = df[(df['TEAM_ABBREVIATION'] == team_2) & (df['GAME_DATE'] == game_date)]
    if not rows_with_value.empty:
        # .iloc[0] is safer than just accessing the first element.  Handles the case where the query returns multiple rows (it shouldn't, but better to be safe).
        return rows_with_value['PTS'].iloc[0]
    else:
        return None  # Handle cases where the opponent's score isn't found.  Important for data integrity.


# Apply the function to create the 'PTS_AWAY' column
df_games_with_season_stats['PTS_AWAY'] = df_games_with_season_stats.apply(
    lambda row: get_opponent_score(row['MATCHUP'], row['GAME_DATE'], df_games_with_season_stats), axis=1
)

In [59]:
df_games_with_season_stats

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,TEAM_ID_opp,W_PCT_opp,PTS_RANK_opp,AST_RANK_opp,REB_RANK_opp,W_PCT_diff,PTS_RANK_diff,AST_RANK_diff,REB_RANK_diff,PTS_AWAY
0,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,1610612752,0.610,19,29,5,0.170,-17,-15,-3,109
1,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,1610612750,0.683,18,15,15,-0.110,-12,-10,3,103
2,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,1610612747,0.573,6,5,18,0.110,12,10,-3,110
3,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,1610612738,0.780,2,14,2,-0.170,17,15,3,132
4,22024,1610612737,ATL,Atlanta Hawks,0022400064,2024-10-23,ATL vs. BKN,W,240,39,...,1610612751,0.390,25,20,11,0.049,-20,-4,-5,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2555,42024,1610612754,IND,Indiana Pacers,0042400202,2025-05-06,IND @ CLE,W,240,44,...,1610612739,0.585,20,8,17,-0.012,-19,-7,11,119
2556,42024,1610612738,BOS,Boston Celtics,0042400212,2025-05-07,BOS vs. NYK,L,240,34,...,1610612752,0.610,19,29,5,0.170,-17,-15,-3,91
2557,42024,1610612743,DEN,Denver Nuggets,0042400222,2025-05-07,DEN @ OKC,L,240,33,...,1610612760,0.695,3,11,27,0.000,11,-8,-20,149
2558,42024,1610612752,NYK,New York Knicks,0042400212,2025-05-07,NYK @ BOS,W,240,37,...,1610612738,0.780,2,14,2,-0.170,17,15,3,90
2559,42024,1610612760,OKC,Oklahoma City Thunder,0042400222,2025-05-07,OKC vs. DEN,W,240,50,...,1610612743,0.695,14,3,7,0.000,-11,8,20,106

In [60]:
df_games_with_season_stats.to_csv('train_data.csv')